# Generated by Django 5.2 on 2025-04-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month_order',
            field=models.IntegerField(help_text='اختر رقم ترتيب هذا الشهر في السنة (1-12)'),
        ),
    ]
