# Generated by Django 5.2 on 2025-04-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_month_month_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month_name',
            field=models.IntegerField(choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'اغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], help_text='اختر اسم الشهر', unique=True),
        ),
    ]
