# Generated by Django 5.2 on 2025-04-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_testgrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestGrade',
        ),
    ]
