# Generated by Django 5.2 on 2025-04-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_delete_testgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlygrade',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlygrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='monthlygrade',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='monthlygrade',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='monthlygrade',
            name='term',
        ),
        migrations.RemoveField(
            model_name='termgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='termgrade',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='termgrade',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='termgrade',
            name='term',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='MonthlyGrade',
        ),
        migrations.DeleteModel(
            name='TermGrade',
        ),
    ]
