# Generated by Django 5.2 on 2025-04-28 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0011_alter_students_academic_levels_options'),
        ('accounts', '0012_alter_customuser_phone_number'),
        ('grades', '0006_remove_monthlygrade_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.IntegerField(choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'اغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], help_text='اختر اسم الشهر', unique=True)),
                ('month_order', models.IntegerField(help_text='اختر رقم ترتيب هذا الشهر في السنة (1-12)')),
            ],
            options={
                'ordering': ['month_order'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments', models.DecimalField(decimal_places=2, max_digits=20)),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('oral', models.DecimalField(decimal_places=2, max_digits=20)),
                ('written', models.DecimalField(decimal_places=2, max_digits=40)),
                ('start_date', models.DateTimeField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Monthly_Grade', to='grades.month')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Monthly_Grade', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Monthly_Grade', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Monthly_Grade', to='accounts.teacherprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Monthly_Grade', to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='TermGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=20)),
                ('exam', models.DecimalField(decimal_places=2, max_digits=30)),
                ('start_date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TermGrade', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TermGrade', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TermGrade', to='accounts.teacherprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TermGrade', to='academics.term')),
            ],
        ),
    ]
