# Generated by Django 5.1.7 on 2025-03-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_guardianprofile_studentguardian_teacherprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_permissions': ()},
        ),
    ]
