# Generated by Django 5.1.1 on 2025-04-01 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'معلم'), ('guardian', 'ولي أمر'), ('supervisor', 'مشرف')], max_length=10),
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guardianprofile',
            name='add_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.supervisorprofile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='add_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.supervisorprofile'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='add_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.supervisorprofile'),
        ),
    ]
