# Generated by Django 5.1.7 on 2025-04-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_user_type_supervisorprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'انثى')], max_length=1),
        ),
    ]
