# Generated by Django 5.1.7 on 2025-04-06 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
