# Generated by Django 5.1.7 on 2025-04-21 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='SupervisorProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
