# Generated by Django 5.1.7 on 2025-03-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_month_subject_class_term'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
    ]
