# Generated by Django 5.1.7 on 2025-03-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_delete_month'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicLevels',
            new_name='AcademicLevel',
        ),
        migrations.RenameModel(
            old_name='AcademicYears',
            new_name='AcademicYear',
        ),
    ]
