# Generated by Django 5.1.7 on 2025-03-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_rename_academiclevels_academiclevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='academic_levels',
            new_name='academic_level',
        ),
    ]
