# Generated by Django 5.1.1 on 2025-04-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_rename_academic_levels_section_academic_level'),
        ('accounts', '0007_alter_customuser_user_type_supervisorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiclevel',
            name='add_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.supervisorprofile'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='add_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.supervisorprofile'),
        ),
        migrations.AddField(
            model_name='class',
            name='add_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.supervisorprofile'),
        ),
        migrations.AddField(
            model_name='section',
            name='add_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.supervisorprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='add_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.supervisorprofile'),
        ),
        migrations.AddField(
            model_name='term',
            name='add_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.supervisorprofile'),
        ),
    ]
