# Generated by Django 5.1.7 on 2025-04-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_students_academic_levels'),
        ('accounts', '0008_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_academic_levels',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile'),
        ),
    ]
