# Generated by Django 5.1.7 on 2025-04-05 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_students_academic_levels_student'),
        ('accounts', '0008_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_academic_levels',
            name='academic_levels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='academics.academiclevel'),
        ),
        migrations.AlterField(
            model_name='students_academic_levels',
            name='registration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='students_academic_levels',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students_academic_levels', to='accounts.studentprofile'),
        ),
    ]
