# Generated by Django 5.1.7 on 2025-04-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_students_academic_levels_academic_levels_and_more'),
        ('accounts', '0009_alter_supervisorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_academic_levels',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students_academic_levels',
            name='academic_levels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_level', to='academics.academiclevel'),
        ),
        migrations.AlterField(
            model_name='students_academic_levels',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_level', to='accounts.studentprofile'),
        ),
    ]
