# Generated by Django 5.1.7 on 2025-04-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_students_academic_levels_is_current_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students_academic_levels',
            options={'ordering': ['-registration_date']},
        ),
    ]
